# Generated by Django 5.0.7 on 2024-08-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
